### ISSUE TITLE
Second call to accept() will give Error [-2007] in function [BsdTcpServerReceive]

### ISSUE THREAD

**Issue by brandonto** [yuzhouliu/Human_Interface_for_Robotic_Control#3] opened 2016-03-08 03:13 UTC
Second call to accept() will give Error [-2007] in function [BsdTcpServerReceive]

To reproduce:
1. Start firmware application on microcontroller
2. Start controller application
3. Connect to microcontroller
4. Disconnect from microcontroller
5. Connect to microcontroller

Please see image below.

![12784743_10153576407791701_365457987_n](https://cloud.githubusercontent.com/assets/4762121/13590895/c9351b4a-e4b1-11e5-8267-6eb524f0afcd.jpg)

**Comment by ducminh296** [comment] 2016-03-08 03:14
thanks. Will look into it.

**Comment by ducminh296** [comment] 2016-03-08 18:17
The issue is fixed by change sl_Accept() to blocking call.

**Closed as completed by ducminh296** 2016-03-08 18:17 UTC
